Update RNA-Seq README.md
Bioinformatics-Research-Network/training-requirements pull request #8
Opened 2022-06-14 01:00 UTC by jmsdao

Added some extra expectations to the requirements to we don't repeat the same points in reviews over and over.

2022-06-17 14:27 UTC, millerh1 requested changes
Hi @jmsdao -- thanks for adding this! Would you mind making the changes requested?

2022-06-17 14:27 UTC, millerh1 commented on RNA-Seq Analysis/README.md
> +	- Top is defined by DEGs having the lowest adjusted p-values, where the absolute log2 fold change is > 1
I think we should only look at padj as log2 fold change (without shrinkage estimation) is misleading in many cases

2022-06-17 14:27 UTC, millerh1 commented on RNA-Seq Analysis/README.md
> +	- Make sure you use an appropriate [ranking metric](https://www.gsea-msigdb.org/gsea/doc/GSEAUserGuideTEXT.htm#_Metrics_for_Ranking) (other metrics outside this document are also acceptable if justi
I think we should probably explicitely tell them to use the wald `stat` column for this

2022-06-18 03:09 UTC, jmsdao commented
@millerh1 I just pushed the changes requested. Please review and merge if appropriate

2022-06-18 12:57 UTC, millerh1 approved these changes
Looks good 😄

2022-06-18 12:57 UTC, merged